# Generated by Django 3.2.17 on 2023-02-10 13:09

import detectwaste.apps.image_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('processed', models.DateTimeField(blank=True, null=True, verbose_name='Processed')),
                ('image', models.ImageField(upload_to=detectwaste.apps.image_processing.models.upload_to, verbose_name='Image')),
                ('status', models.CharField(choices=[('i', 'In progress'), ('p', 'Processed')], default='i', max_length=1, verbose_name='Status')),
                ('categories', models.ManyToManyField(blank=True, to='image_processing.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Processed Image',
                'verbose_name_plural': 'Processed Images',
                'ordering': ['-created'],
            },
        ),
    ]
