# Generated by Django 3.2.17 on 2023-02-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Processed Image', 'verbose_name_plural': 'Processed Images'},
        ),
        migrations.RenameField(
            model_name='processedimage',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='processedimage',
            old_name='processed',
            new_name='processed_at',
        ),
    ]
